[package]
version = "0.1.3"
title = "cuOpt Microservice Examples"
description="A set of UI based examples using the NVIDIA cuOpt Microservice"

readme  = "docs/README.md"
changelog = "docs/CHANGELOG.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

category = "Example"

keywords = ["kit", "example", "cuopt", "isaac", "sim"]
writeTarget.kit = true

[dependencies]
"omni.kit.uiapp" = {}
"omni.isaac.ui" = {}
"omni.isaac.core" = {}
"omni.isaac.debug_draw" = {}
"omni.cuopt.microservice" = {}
"omni.cuopt.visualization" = {}


[[python.module]]
name = "omni.cuopt.examples.costmat"

[[python.module]]
name = "omni.cuopt.examples.wpgraph"

[[python.module]]
name = "omni.cuopt.examples.warehouse_transport_demo"
