[package]
version = "0.1.3"
title = "cuOpt Simple Visualization"
description="Extension demonstrating the visualization of cuOpt specific data in Isaac Sim"

readme  = "docs/README.md"
changelog = "docs/CHANGELOG.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

category = "Example"

keywords = ["kit", "example", "cuopt", "isaac", "sim", "visualization"]
writeTarget.kit = true

[dependencies]
"omni.kit.uiapp" = {}
"omni.isaac.core" = {}
"omni.cuopt.microservice" = {}

[[python.module]]
name = "omni.cuopt.visualization"
