[package]
version = "0.1.3"
title = "cuOpt Simple Interface"
description="Extension demonstrating a simple interface with the cuOpt Microservice"

readme  = "docs/README.md"
changelog = "docs/CHANGELOG.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

category = "Example"

keywords = ["kit", "example", "cuopt", "isaac", "sim", "interface"]
writeTarget.kit = true

[dependencies]
"omni.kit.uiapp" = {}


[[python.module]]
name = "omni.cuopt.microservice"